---

- name: Prepare datasource file
  template:
    src: templates/sample.json
    dest: /tmp/
  
- name: push datasource file to grafana
  shell: >
    curl -X "POST" "http://localhost:3000/api/datasources"     
    -H "Content-Type: application/json"      
    --user admin:{{ GRAFANA_ADMIN_PASSWORD }}
    --data-binary @/tmp/sample.json
