---
grafana_url: "http://localhost:3000"
grafana_user: admin
grafana_password: "GrafanaAdminPassword"
org_id: "1"

data_source:
  - name: influxdb
    ds_type: "influxdb"
    url: "http://localhost:8086"
    user: "influx_user"
    password: "StrongPassword"